name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: exec scripts/build_all.sh
        run:  sudo ./scripts/build_all.sh

      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/system.img