name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Install debootstrap 
        run:  |
              git clone --depth=1 https://salsa.debian.org/installer-team/debootstrap/
              sudo chmod 0755 debootstrap/debootstrap
              sudo ln -s $(realpath debootstrap/debootstrap) -t /usr/bin
              sudo ln -s $(realpath debootstrap) -t /usr/share/

      - name: exec scripts/build_all.sh
        run:  sudo bash -c "cd scripts && chmod +x -R . && ./build_all.sh"

      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/system.img
